publication/courses/urls.py
from django.urls import path
from .views import *

app_name ="courses"
urlpatterns =[
    path('',SubjectListView.as_view(), name="subjectlist"),
    path('<slug:slug>',CourseListView.as_view(), name="courselist"),
    path('<str:subject>/<slug:slug>',ModuleListView.as_view(), name="modulelist"),
    path('<str:subject>/<str:slug>/create/',ModuleCreateView.as_view(), name="modulecreate"),
    path('<str:subject>/<str:course>/<slug:slug>',ModuleListViewDetail.as_view(), name="modulelistdetail"),
    path('<str:subject>/<str:course>/<slug:slug>/update',ModuleUpdateView.as_view(), name="moduleupdate"),
    path('<str:subject>/<str:course>/<slug:slug>/delete',ModuleDeleteView.as_view(), name="moduledelete"),
    
]

publication/publication/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
# detail view to display a single course
#from courses.views import CourseListView
from django.conf import Settings, settings
from django.conf.urls.static import static

from publication.settings import MEDIA_ROOT, MEDIA_URL
from django.views.generic import RedirectView
#from django.conf.urls import url
#from courses.views import ManageCourseListView


urlpatterns = [
    #path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    #path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
    path('course/', include('courses.urls')),
    #path('course/', ManageCourseListView.as_view(), name='subjectlist'),
    
    # Rest framework
    #path('api-auth/', include('rest_framework.urls')),
    #path('api/', include('courses.api.urls', namespace='api')),


    #url(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publication/courses/models.py
import os
from http.client import responses
from unicodedata import name
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse






img = 0
img_sub=0
vid = 0
fil = 0
fil_pre=0

def rename_image(instance, filename):
    '''instance here is the user of the profile class '''
    global img
    upload_to = 'image/'
    # recuperer l'extension de l'image et traiter
    #img.png
    extension = filename.split('.')[-1]
    extension = filename.split('.')[-1]
    list = ['jpeg', 'jpg', 'png']
    for elm in list:
        if elm==extension:
            img = img+1
            filename = "course_images/img-{}.{}".format(img, extension)
            return os.path.join(upload_to,  filename)
    return print('format error')


def rename_image_subject(instance, filename):
    '''instance here is the user of the profile class '''
    global img_sub
    upload_to = 'image/'
    # recuperer l'extension de l'image et traiter
    #img.png
    extension = filename.split('.')[-1]
    extension = filename.split('.')[-1]
    list = ['jpeg', 'jpg', 'png']
    for elm in list:
        if elm==extension:
            img_sub = img_sub+1
            filename = "course_images/subject/img-{}.{}".format(img_sub, extension)
            return os.path.join(upload_to,  filename)
    return print('format error')




def rename_image_course(instance, filename):
    '''instance here is the user of the profile class '''
    global img_sub
    upload_to = 'image/'
    # recuperer l'extension de l'image et traiter
    #img.png
    extension = filename.split('.')[-1]
    extension = filename.split('.')[-1]
    list = ['jpeg', 'jpg', 'png']
    for elm in list:
        if elm==extension:
            img_sub = img_sub+1
            filename = "course_images/subject/img-{}.{}".format(img_sub, extension)
            return os.path.join(upload_to,  filename)
    return print('format error')


def rename_video(instance, filename):
    '''instance here is the user of the profile class '''
    global vid 
    upload_to = 'video/'
    vid=vid+1
    # recuperer l'extension de l'image et traiter
    #img.png
    extension = filename.split('.')[-1]
    list = ['mp4', 'mkv']
    for elm in list:

        if elm==extension:
            filename = "course_video/video-.{}".format(extension)
            return os.path.join(upload_to,  filename)
    return print('format error')
        
def rename_file(instance, filename):
    global fil
    '''instance here is the user of the profile class '''
    upload_to = 'file/'
    # recuperer l'extension de l'image et traiter
    #img.png
    extension = filename.split('.')[-1]
    list = ['doc', 'pdf', 'docx']
    for elm in list:
        fil = fil+1
        if elm==extension:
            filename = "course_file/file-{}.{}".format(fil, extension)
            return os.path.join(upload_to,  filename)
    return print('format error')

def rename_present_file(instance, filename):
    global fil_pre
    '''instance here is the user of the profile class '''
    upload_to = 'file/'
    # recuperer l'extension de l'image et traiter
    #img.png
    extension = filename.split('.')[-1]
    list = ['doc', 'pdf', 'docx']
    for elm in list:
        fil_pre = fil_pre+1
        if elm==extension:
            filename = "course_present_file/file-{}.{}".format(fil_pre, extension)
            return os.path.join(upload_to,  filename)
    return print('format error')








# Create your models here.
class Subject(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True) #aide a enlever les espaces entre les mots
    description = models.TextField()
    image = models.ImageField(upload_to=rename_image_subject, blank=True)

    
    # mettre les fonction pour chaque slug
    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


 #related_name='subject'(ie c'est le nom de la relation entre Subject et Courses)   
class Course(models.Model):
    owner = models.ForeignKey(User, related_name='courses_created', on_delete=models.CASCADE) 
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='course')
    course_id = models.CharField(unique=True, max_length= 40)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to=rename_image_course, blank= True)
    description = models.TextField(max_length=500 )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
  


class Module(models.Model):
    module_id = models.CharField(unique=True, max_length=40)
    subject =  models.ForeignKey(Subject, on_delete= models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)    #qui a creer ce module/cours 
    course = models.ForeignKey(Course, on_delete= models.CASCADE, related_name='module' ) # related_name pck veut delete entre la table module et course
    name = models.CharField(max_length= 100)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    position = models.PositiveSmallIntegerField(verbose_name= 'chapitre_no') # verbose name(cmt appele ce champ)

    video = models.FileField(upload_to=rename_video, null=True, blank=True, verbose_name="video course")
    present_file = models.FileField(upload_to=rename_present_file, null=True, blank=True, verbose_name="presenting file")
    pdf_course = models.FileField(upload_to=rename_file, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    #fppc =models.FileField(upload_to= "FPPC", null= True, blank= True, verbose_name="fiche de presentation")  # fic pres pc(FPPC)
    #pdf = models.FileField(upload_to= "PDF", null= True, blank= True, verbose_name="cours en pdf")
    
    #order = OrderField(blank=True, for_fields=['course'])


    # class pour ordonner les modules (chap/lesson)
    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("courses:modulelist", kwargs={"slug": self.course.slug, "subject":self.subject.slug})    

    
class Comment(models.Model):
    name_module = models.ForeignKey(Module, null=True, on_delete=models.CASCADE,related_name='comments')
    name_com =models.CharField(max_length=100, blank=True)
    #response = models.ForeignKey('Commentaire',null=True, blank=True, on_delete= models.CASCADE, related_name='reponses')
    #utiliser Commentaire pour faire des reponses
    owner =models.ForeignKey(User, on_delete = models.CASCADE)
    body = models.TextField(max_length=500)
    created =models.DateTimeField(auto_now_add=True) 
    
    #modifier le nom du commentaire
    def save(self, *args, **kwargs):
        self.name_com = slugify("commenter par" + str(self.owner) + "a" + str(self.created))
        super().save(*args, **kwargs)

    #nom a retourner
    def __str__(self):
        return self.name_com 

    #classer les commentaires par date 
    class  Meta:
        ordering = ['-created']   


class  Response(models.Model):
    name_com = models.ForeignKey(Comment, on_delete= models.CASCADE, related_name='responses')  
    body = models.TextField(max_length=500)
    owner = models.ForeignKey(User, on_delete=models.CASCADE) 
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reponse a" + str(self.name_com.name_com)     

publication/courses/forms.py
#from tkinter import Widget
from django import forms 
from .models import Module, Comment, Response 

#__all__
class ModuleForm(forms.ModelForm):
    class Meta():
        model = Module 
        fields = ['module_id','name', 'video', 'present_file', 'pdf_course', 'position' ]


class ComForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'body'}
        labels = {'body': 'Comment'} 
        widgets = {
            'body':forms.Textarea(attrs={
                'class': 'form-control',
                'rows':4,
                'cols':70,
                'placeholder':'Entrez votre commentaire ici.'
            })
        }


class RepForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = {'body',}
        labels = {'body': 'responses'}
        widgets = {
            'body':forms.Textarea(attrs={
                'class': 'form-control',
                'rows':2,
                'cols':10,
                'placeholder':'Response here'
            })
        }

publication/courses/views.py
from django.shortcuts import render
from .models import *
from django.views.generic import DetailView, ListView, DeleteView, UpdateView, CreateView, FormView
from .forms import ModuleForm, ComForm, RepForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy

# Create your views here.

class SubjectListView(ListView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'courses/subject_list.html'


class CourseListView(DetailView): # car chq suject est lier a un cour 
    context_object_name = 'subject' #(ie on peut utiliser Subject au lieu de Cour )
    model = Subject
    template_name = 'courses/subject_detail.html'


class ModuleListView(DetailView):
    context_object_name = 'courses'
    model = Course
    template_name = 'courses/course_detail.html'


class ModuleListViewDetail(DetailView, FormView):
    context_object_name = 'module'
    model = Module
    template_name = 'courses/module_detail.html'
    form_class = ComForm
    second_form_class = RepForm
    
    def get_context_data(self, **kwargs):
        context = super(ModuleListViewDetail, self).get_context_data(**kwargs)

        if 'form' not in context :  #si le form est dans le context
            context['form'] =self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()  

        return context
    
    

    # ces fonctions permette de valider
    def form_valid(self, form):
        self.object = self.get_object() #les choses necessaire pour le stockage en bd
        fv = form.save(commit=False)
        fv.owner = self.request.user
        fv.name_module = self.object.comments.name
        fv.name_module_id = self.object.id
        fv.save()
        return HttpResponseRedirect(self.get_success_url())  

    def form_valid2(self, form):
        self.object = self.get_object()
        fv = form.save(commit=False)
        fv.owner = self.request.user
        fv.name_com_id = self.request.POST.get('comment_id')
        fv.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        self.object = self.get_object()
        subject = self.object.subject
        course = self.object.course
        return reverse_lazy('courses:modulelistdetail', kwargs={
            'subject':subject,
            'course':course, 
            'slug': self.object
        })         


    #lorsque l'utilisateur doit poster
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.form_class

            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'  
        form = self.get_form(form_class) 

        if form_name =='form'and form.is_valid():
            print('nouveau commentaire')
            return self.form_valid(form)  

        if form_name =='form2'and form.is_valid():
            print('nouvelle reponse')
            return self.form_valid2(form)   

                      

 #creer un objet de course
class ModuleCreateView(CreateView):
    form_class = ModuleForm
    context_object_name = 'courses'
    model = Course
    template_name = 'courses/module_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        subject = self.object.subject
        #course = self.object.course
        return reverse_lazy('courses:modulelist', kwargs= {'subject':subject, 'slug': self.object.slug})
        

    def form_valid(self, form, *args,**kwargs):
        self.object = self.get_object()
        md =form.save(commit= False)
        md.owner = self.request.user      # object que je veux enregistrer
        md.subject = self.object.subject
        md.course = self.object
        md.save()
        return HttpResponseRedirect(self.get_success_url())

class ModuleUpdateView(UpdateView):
    fields = ('name','position', 'present_file','pdf_course')
    context_object_name = 'module'
    model = Module
    template_name = 'courses/module_update.html'

class ModuleDeleteView(DeleteView):
    model = Module
    context_object_name = "module"
    template_name = 'courses/module_delete.html'

    def get_success_url(self):
        subject = self.object.subject
        course = self.object.course
        return reverse_lazy("courses:modulelist", kwargs ={'subject':subject, 'slug':course.slug})

publication/courses/templates/courses/course_detail.html
{% extends 'bases.html' %}

{%block content%} 

    <header>
        <!-- Sidebar -->
        <div style="float: right; width: 25%; margin-top: 30px;">
            {%for mod in courses.module.all %}
                {%if user.is_authenticated%} 
                
                    <a href="{%url 'courses:modulelistdetail' slug=mod.slug course=courses.slug subject=courses.subject.slug%}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
                        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Module {{mod.position}} {{mod.name}}</span>
                    </a>
                {%else%}
                    <a href="#" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
                        <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Module {{mod.position}} {{mod.name}}</span>
                    </a>
                {%endif%}
    
            {%endfor%}
            {%if user.is_superuser%}
        
                <button type="button" class="btn btn-primary mb-3" style="width: 100%;">
                    <a href="{% url 'courses:modulecreate' subject=courses.subject slug=courses%}" style="text-decoration: none;color: white;">create Module</a>
                </button>
            {%endif%}
        </div>
        <!-- Sidebar -->
      
        <!-- Navbar -->
        
        <!-- Navbar -->
    </header>
      
      <!--Main Navigation-->
      
      <!--Main layout-->
    
      <div class="container">
    
        <div class="row" >
    
            {%for mod in courses.module.all %}
                
                    <div class="col-md-3 " style="margin-top: 30px; margin-bottom: 50px;">
                                  
                                    
                            <div class="card cardre" style="border: 1px solid black; margin-bottom: 150px;">
                                {%if user.is_authenticated%}  
                                    <a href="{%url 'courses:modulelistdetail' slug=mod.slug course=courses subject=courses.subject%}">
    
                                        <div class="title" style="width: 100%; color: #000000; background: #212529; text-transform: uppercase; padding: 5px; text-align: center;">
                                            <h5 class="subTitle" style="color: #000000;">
                                                <a href="{%url 'courses:modulelistdetail' slug=mod.slug course=courses.slug subject=courses.subject.slug%}" style="text-decoration: none; color: white;">{{mod.name}}</a>
                                            </h5>
                                        </div>
                                        <div class="card-body">
                                            <a href="" style="text-decoration: none;">
                                                <h5 class="card-title" style="color: #212529;">{{mod.name}}</h5>
                                            </a>
                                            {%if mod.video%}
                                                {{mod.video.url}}
                                            {%endif%}
                                            <p class="card-text">{{mod.description}}<br>This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                                        </div>
                                    </a>
    
                                {%else%}
                                    <div class="title" style="width: 100%; color: #000000; background: #212529; text-transform: uppercase; padding: 5px; text-align: center;">
                                        <h5 class="subTitle" style="color: white;">
                                           {{mod.name}}
                                        </h5>
                                    </div>
                                    <p style="margin: 3px;">to follow this course, you might be connected <a href="{%url 'login'%}">login</a></p>
                                {%endif%}
                            </div>
                        
                    
                    </div>
            {%empty%}
                <div class="col-md-12" style="margin-bottom: 150px;">
                    <h1>No module in this course</h1><br>
                    
                    <p>please we are updating  this subject for the moment </p> 

                    <p> are so sorry for that </p> 

                    <p>You can select another subject by clicking on the link below </p>

                    <a href="{% url 'courses:courselist' slug=courses.subject.slug%}">courses</a>
                
                    </div>
                
            {%endfor%}
        </div>
      </div>
      <!--Main layout-->
        
    





{% endblock%}

publication/courses/templates/courses/module_create.html
{% extends 'bases.html' %}

{%block content%} 
    <form method="POST">
        {% csrf_token %} 
        {{ form.as_p}} 
        <input type="submit" value="confirmer la creation" > 
    </form>

{% endblock%}

publication/courses/templates/courses/module_delete.html
{% extends 'bases.html' %}

{%block content%} 
<h1>Etes vous sure de vouloir supprimer </h1>
    <form method="POST">
        {% csrf_token %} 
        <input type="submit" value="supprimer definitivement" > 
        <a href="{% url 'courses:modulelistdetail' slug=module.slug course=module.course.slug subject=module.subject.slug %}">annuler la suppression</a>
    </form>

{% endblock%}

publication/courses/templates/courses/module_detail.html
{%extends 'bases.html'%}
{%load static%}


{%block content%}





    <!-- Sidebar -->
    <div style="float: right; width: 25%; margin-top: 83px;" >    
        {%for mod in module.course.module.all %}           
            <a href="{% url 'courses:modulelistdetail' slug=mod.slug course=mod.course subject=mod.subject %}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
                <i class="fas fa-tachometer-alt fa-fw me-3" ></i><span>Module {{mod.position}}: {{mod.name}}</span>
            </a>
        {%endfor%}
        {%if user.is_superuser%}
            <button type="button" class="btn btn-primary mb-3" style="width: 100%;">
                <a  class="fas fa-tachometer-alt fa-fw me-3" href="{% url 'courses:modulecreate' subject=module.subject slug=module.course %}"style="text-decoration: none;color: white;">create Module</a>
            </button>
        {% endif %}
        
    </div>
    <!-- Sidebar -->
  
    <!-- Navbar -->
    
    <!-- Navbar -->

  
  <!--Main Navigation-->
  
  <!--Main layout-->
  <main style="  width: 70%; margin-left: 30px;">
    <div class="container-fluid pt-3">
        <h2 style="text-transform: uppercase;">{{module.name}}</h2>
        <p>module {{module.position}} has been created by {{module.course.owner}} </p>
        {%if module.video%}
            <video  class="img-fluid" autoplay loop controls>
                <source src="{{module.video.url}}" >
                <p class="warning">Your browser does not support HTML5 video.</p>
            </video>          
        {%endif%}
        <div style="margin-top: 15px; margin-bottom: 30px;">
            {%if module.present_file%}
                <button type="button" class="btn btn-info mb-2" >
                    <a href="{{ module.present_file.url }}" class="button" style="text-decoration: none; color: white;">Download the presenting file</a>
                </button>
            {%endif%}
            {%if module.pdf_course%}
                <button type="button" class="btn btn-info mb-2">
                    <a href="{{ module.pdf_course.url }}" class="button" style="text-decoration: none; color: white;">Download the pdf file</a>
                </button>
            {%endif%}
            {%if module.video%}
                <button type="button" class="btn btn-primary mb-2">
                    <a href="{{ module.video.url }}" class="button" style="text-decoration: none; color: white;">Download video</a>
                </button>
                <br>
            {%endif%}
            {% if user.is_superuser%}
                <button type="button" class="btn btn-primary mb-2">
                    <a href="{% url 'courses:moduleupdate' subject=module.subject.slug course=module.course.slug slug=module.slug %}" style="text-decoration: none; color: white;">modufied the module</a>
                </button>
        
        
                <button type="button" class="btn btn-danger mb-2">
                    <a href="{% url 'courses:moduledelete' subject=module.subject.slug course=module.course.slug slug=module.slug %}" style="text-decoration: none; color: white;">delete the module</a></a>
                </button>
            {%endif%}

        </div>
        
        <div style="margin-bottom: 30px; padding: 15px;">
            <h4>Post your comment here</h4>
            <form method="post">
                {%csrf_token%}
                <div class="form-group">
                    {{form.as_p}}
                    <input type="submit" name="form" value="comment" class="btn btn-primary btn-sm">
                </div>
            </form>

            {% for comment in module.comments.all %} 
                <h4>
                    {{comment.owner}} 
                    <small>
                        <i> has been podted the {{comment.created}}</i>
                    </small>
                </h4>
                <p>{{comment.body}}</p>
                

                {%for resp in comment.responses.all%}
                    <h5>
                        {{resp.owner}} 
                        <small>
                            <i> has been reply the {{resp.created}}</i>
                        </small>
                    </h5>
                    <p>{{resp.body}}</p>
                {%endfor%}

                <form method="post">
                    {%csrf_token%}
                    <input type="hidden" name="comment_id" value="{{comment.id}}">
                    {{form2.as_p}}
                    <input type="submit" name="form2" value="Response" class="btn btn-warning btn-sm">
                </form>
            {%endfor%}

        </div>


        
        
        
        
        
    </div>
  </main>
  <!--Main layout-->







        





        

        
            
        
           






        

   
{%endblock%}

publication/courses/templates/courses/subject_detail.html
{% extends 'bases.html' %}
{%load static%}

{%block content %} 


    <div class="container">
        <link rel="stylesheet" href="{% static 'css1.css' %}"> 
        <div class="row" >
            {%for mod in subject.course.module.all%}
                <a href="{%url 'courses:moduledetail' slug=mod.slug course=mod.course subject=mod.subject%}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
                <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Module {{mod.}} {{mod.title}}</span>
                </a>
            {%endfor%}
            {%for course in subject.course.all%}
                <div class="col-md-3 " style="margin-top: 30px; margin-bottom: 50px;">
                    
                    
                        <div class="card cardre" style="border: 1px solid black;">
                            <a href="{% url 'courses:modulelist' slug=course.slug subject=subject.slug %}">
                                {%if course.image%}
                                    <img class="card-img-top subImg" src="{{course.image.url}}" alt="Lights" style="width:100%; height: 250px;">
                                {%endif%}

                                <div class="title" style="width: 100%; color: #000000; background: #212529; text-transform: uppercase; padding: 5px; text-align: center;">
                                    <h5 class="subTitle" style="color: #000000;">
                                        <a href="{% url 'courses:modulelist' slug=course.slug subject=subject.slug %}" style="text-decoration: none; color: white;">{{course.name}}</a>
                                    </h5>
                                </div>
                                <div class="card-body">
                                    <a href="" style="text-decoration: none;">
                                        <h5 class="card-title" style="color: #212529;">{{course.name}}</h5>
                                    </a>
                            
                                    <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                                </div>
                            </a>
                          </div>
                        
                          
                </div>
            {%empty%}
                <div class="col-md-12" style="margin-bottom: 150px;">
                    <h1>No course in this subject</h1><br>
                    
                    <p>please we are updating  this subject for the moment </p> 

                    <p> are so sorry for that </p> 

                    <p>You can select another subject by clicking on the link below </p>

                    <a href="{% url 'courses:subjectlist' %}">Subject</a>
               
                </div>
            
                

            {%endfor%}
    
    
    
          
        </div>
    
        
    
    
        
    </div>




{% endblock%}

publication/courses/templates/courses/subject_list.html
{% extends 'bases.html' %}
{%load static%}

{% block content %}

    






    <div class="container">
        <link rel="stylesheet" href="{% static 'css1.css' %}"> 
        <div class="row" >
            {%for subject in subjects %}
                <div class="col-md-3 " style="margin-top: 30px; margin-bottom: 50px;">
                    
                    {%if subject.image%}
                        <div class="card cardre" style="border: 1px solid black;">
                            <a href="{% url 'courses:courselist' slug=subject.slug%}">
                                <img class="card-img-top subImg" src="{{subject.image.url}}" alt="Lights" style="width:100%; height: 250px;">
                                <a href="{% url 'courses:courselist' slug=subject.slug%}">
                                    <div class="title" style="width: 100%; color: #000000; background: #212529; text-transform: uppercase; padding: 5px; text-align: center;">
                                        <h5 class="subTitle" style="color: #000000;">
                                            <a href="{% url 'courses:courselist' slug=subject.slug%}" style="text-decoration: none; color: white;">{{subject.name}}</a>
                                        </h5>
                                    </div>
                                </a>
    
                                <div class="card-body">
                                    <h5 class="subTitle" style="color: #000000;"><a href="{% url 'courses:courselist' slug=subject.slug%}" style="text-decoration: none; color: #212529;">{{subject.title}}</a></h5>
                                    <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                                </div>
                            </a>
                          </div>
                        
                    {%endif%}
                    
                            
                    
                </div>
            {%endfor%}
    
    
    
          
        </div>
    
        
    
    
        
    </div>
    





{% endblock %}